---
site_name: docs-template  # yamllint disable-line
site_description: ...
site_url: >
  https://inovintell.github.io/docs-template
repo_url: >
  https://github.com/inovintell/docs-template
repo_name: >
  'inovintell/docs-template'  # yamllint disable-line


nav:
  - Overview: README.md
  - Templates:
      - template:
          - Setup: template/setup.md
          - Functionality and Configuration: template/functionality.md
      - py-template (Python):
          - Setup: py-template/setup.md
          - Functionality and configuration: py-template/functionality.md
          - Python versioning: py-template/version.md
          - Adjusting coverage: py-template/coverage.md
          - Private releases: py-template/private.md
          - Integration with existing projects: py-template/integration.md
  - Template initialization: initialization.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md

theme:
  name: material
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
  features:
    - navigations.tabs
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - autorefs
  - section-index
  - minify:
      minify_html: true
      htmlmin_opts:
        remove_comments: true

# https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
